Initial checkin with custom collection list class
fast-food-finder-associates/FastFoodFinder pull request #27
Opened 2019-03-11 23:08 UTC by edtyler

All files are under datastore sub-directory. See dbtest.cpp for usage details.
Essentially, you will instantiate :
UserDataStore Users;
RestaurantDataStore Restaurants;
TripDataStore Trips;

and then simply treat these as collections of the various objects. The colections are populated from disk when they come into scope and will be staged back to disk when they go out of scope.

2019-03-13 04:31 UTC, ChrisRzech requested changes
These are my initial thoughts after glancing at it
Couple things that need to be attended to:
* These files must be added to the `.pro` file in order to use them within Qt Creator
* If we want our data to be saved throughout program executions, they **CANNOT** be added to a `.qrc` file. The reason this is is because Qt compiles their `.qrc` file into the executable so access time is much faster (accessing memory is worse than smoking). A similar solution for the login credential file can be applied here, but there may be other complications (such as how would the user get the initial file in the first place).
* I'm not sure how I feel about `void` parameters. `void foo(void)` is the same thing as `void foo()` in C++. Usually `void` parameters are a C thing to do. It makes no difference to functionality, but visually it stunned me to see it.
🔥 🔥 /5

2019-03-13 06:56 UTC, ChrisRzech requested changes
A more thorough look into the classes and their inner-workings. Doesn't look like there is much functionality in terms of editing a restaurant. Remember, the admin tool should be able to edit almost any aspect of a restaurant.
(Stopped reviewing at `RestaurantDataStore`)
🔥 🔥 🔥 🔥 /5

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.cpp
> +int Restaurant::sm_NextNumber = 1;
Can we get a comment saying what this is?

Example:
```suggestion
//Static member of Restaurant
int Restaurant::sm_NextNumber = 1;
```

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.cpp
> +   if (this == &rhs) {
Braces should be on it's own line

```suggestion
   if (this == &rhs)
   {
```

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.cpp
> +    m_ReferencedByTrips.push_back(TripNumber);
Function doesn't look finished. This solution should work as intended
```suggestion
    if(std::find(m_ReferencedByTrips.begin(), m_ReferencedByTrips.end(), TripNumber) == m_ReferencedByTrips.end())
    {
        m_ReferencedByTrips.push_back(TripNumber);
        return true;
    }
    
    return false;
```

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.cpp
> +//! \author edt (2/7/18)
Not sure if the year of this date is wrong

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.cpp
> +//! \author edt (2/7/18)
Another potentially wrong year?

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.h
> +#ifndef __Restaurant_H_INCL__
As per the team rules, make sure these are `#pragma once` instead

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.cpp
> +Restaurant::~Restaurant()
Unnecessary destructor definition: suggest to remove

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.h
> + * TODO: Add class description
Class description missing. Can we also add a description of each member variable for ease of understanding what the functions do just so we have a clear idea of what each one mean? (on initial look, `m_nNumber` was unclear but figured out it was the restaurant ID)

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.h
> +    virtual ~Restaurant();
Not sure why destructor is declared as virtual, or even explicitly declared as a matter of fact. In reality, `Restaurant` should be declared as a `final` class.

But this makes no difference, just nitpicking for code review's sake.

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/Restaurant.h
> +    bool                m_bInitialized;
For example, I'm not completely sure what this variable means at first glance. We need some sort of documentation for these variables. Could probably start doing the DOXYGEN for these classes

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/RestaurantDataStore.h
> +#ifndef __RESTURANTDATASTORE_H_INCL__
`#pragma once` due to team rules

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/RestaurantDataStore.h
> +class RestaurantDataStore
I thought this class was going to be a singleton? I was expecting this class to contain a static list (like it does) throughout the whole program execution. Looks like I'm able to create multiple `RestaurantDataStore`s within a single program execution. Otherwise, this whole "class" can be a single function to load the data from a file into a global static container.

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/RestaurantDataStore.h
> +    MyDblLinkList<Restaurant> list;
This is where the functionality wrappers would come in handy, we shouldn't have access directly to the list to restrict tempering with the restaurants directly.

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/RestaurantDataStore.cpp
> +static const int nMaxRestaurantInputLine = 500;
unused variable?

2019-03-13 06:56 UTC, ChrisRzech commented on src/datastore/RestaurantDataStore.h
> +    RestaurantDataStore(const RestaurantDataStore& src);
If going for the singleton approach, better to just `= delete` this and `operator=`
```suggestion
    RestaurantDataStore(const RestaurantDataStore& src) = delete;
```

2019-03-14 00:46 UTC, AAE1997 commented on src/datastore/RestaurantDataStore.h
> +    RestaurantDataStore(const RestaurantDataStore& src);
Will "delete" erase all data that is in the database along with data that has been added by the admin (via Copy Constructor)?

2019-03-14 00:47 UTC, AAE1997 commented
Will "delete" erase all data that is in the database along with data that has been added by the admin (via Copy Constructor)?

2019-03-14 01:53 UTC, ChrisRzech commented
Where exactly are you seeing this delete functionality? If you are talking about a specific line/function, you should've written your comment on that line.

2019-03-14 02:12 UTC, RogChav commented on src/datastore/RestaurantDataStore.h
> +    RestaurantDataStore(const RestaurantDataStore& src);
I'm pretty sure he means this line @ChrisRzech 

```suggestion
    RestaurantDataStore(const RestaurantDataStore& src)  = delete;;
```

2019-03-17 01:58 UTC, ChrisRzech approved these changes
We are approving this for the sake of progression for other stories. This branch, however, will **NOT** be deleted to be left for future commits by the author.

2019-03-17 01:59 UTC, merged