Admin ui v1.1
fast-food-finder-associates/FastFoodFinder pull request #32
Opened 2019-03-15 16:26 UTC by RogChav

### Key features
* NavBar switches states from menu state to inventory management state (admin tools)
* On switch it sets search to the default selection 
* All the NavItem buttons are routed to their views
* Made two functions to change NavBar between states

### Future Improvements
* The states functions can possibly be changed to one function that switches based on input, so both options would be available within a switch statements which would allow more states to be added down the line

### Notes
* Didn't make the functions just one toggle function incase we decide to add a different toggle down the road
* Had trouble with QPalette setting the selection color to the default inactive/ disabled colors. Also was setting the row on the wrong line, made it change within singleshot and set the Qt::highlight color of all the states to the same color

2019-03-15 18:26 UTC, ChrisRzech requested changes
Some things on these changes are already on master. This branch should rebase first, maybe that might fix it. After that, I can review it again.

2019-03-16 04:10 UTC, ChrisRzech requested changes
You need some milk
🔥 🔥 🔥 /5

2019-03-16 04:10 UTC, ChrisRzech commented on src/widgets/navitem.cpp
> -
Undo

2019-03-16 04:10 UTC, ChrisRzech commented on src/widgets/navitem.cpp
> +
Undo

2019-03-16 04:10 UTC, ChrisRzech commented on src/widgets/navitem.cpp
> +void NavItem::enterEvent(QEvent* e)
Undo

2019-03-16 04:10 UTC, ChrisRzech commented on src/widgets/navitem.cpp
> +void NavItem::leaveEvent(QEvent* e)
Undo

2019-03-16 04:10 UTC, ChrisRzech commented on src/widgets/navitem.ui
> +    <number>0</number>
Undo all changes in this file, unless there is a reason

2019-03-16 04:10 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +#include <QResizeEvent>
Remove

2019-03-16 04:10 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +    m_navbar->addItem("\uf03A", "View\nRestaurants");
Do we want to use this icon?

2019-03-16 04:10 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +/*Swich views for stacks in mainView within the mainWindow page (page 1) in centralStack*/
This will kill me later on. Add some spaces between the `*` and the words
```suggestion
/* Swich views for stacks in mainView within the mainWindow page (page 1) in centralStack */
```

2019-03-16 04:10 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +//}
Remove this commented function

2019-03-16 04:10 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +     <number>3</number>
Undo

2019-03-16 04:11 UTC, RogChav commented on src/windows/mainwindow.cpp
> +    m_navbar->addItem("\uf03A", "View\nRestaurants");
Going to check.

2019-03-16 04:16 UTC, RogChav commented on src/widgets/navitem.ui
> +    <number>0</number>
Honestly thought I accepted all of your changes to the file, because I haven't changed anything

2019-03-16 04:40 UTC, ChrisRzech requested changes
Just a little more
🔥 🔥 /5

2019-03-16 04:40 UTC, ChrisRzech commented on src/widgets/navbar.cpp
> +    /* Setting background color for highlight - when NavItem is selected this will be it's background color */
Why is this whole section in `NavBar::addItem()`? Why not in the ctor?

2019-03-16 04:40 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +    m_navbar->setCurrentRow(0);
Necessary?

2019-03-16 04:40 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +void MainWindow::changeNavInvManage()
We can condense this into 1 function that takes a `bool` and uses ternary operators NOT an `if-else` statement like
```cpp
void MainWindow::something(bool)
```

2019-03-16 04:50 UTC, RogChav commented on src/widgets/navbar.cpp
> +    /* Setting background color for highlight - when NavItem is selected this will be it's background color */
Good question, that was my intention. My bad, editing this now

2019-03-16 04:58 UTC, RogChav commented on src/windows/mainwindow.cpp
> +    m_navbar->setCurrentRow(0);
no, removed

2019-03-16 05:28 UTC, ChrisRzech requested changes

2019-03-16 05:28 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +        <string notr="true">* {
Do not use the `*` widget specifier for stylesheets unless used with certainty. This will only cause future bugs that we might not be able to trace back. Use `QWidget#searchView` instead. The same goes for all instances this `*` used.

2019-03-16 05:29 UTC, RogChav commented on src/windows/mainwindow.ui
> +        <string notr="true">* {
Understood

2019-03-16 06:24 UTC, ChrisRzech requested changes
Smol
🔥 /5

2019-03-16 06:24 UTC, ChrisRzech commented on src/windows/mainwindow.hpp
> +    enum class viewStates { MAIN, ADMIN };
Can we get a "class" style naming for enums? `ViewStates`

2019-03-16 06:24 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
Something happened here; looks like some text formatting got sucked into the commit.

2019-03-16 06:28 UTC, RogChav commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
using &quot; in place of "

2019-03-16 06:29 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
Are you saying you're going to keep it? You don't need either of them anyway

2019-03-16 06:29 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
Oh nvm

2019-03-16 06:29 UTC, RogChav commented on src/windows/mainwindow.hpp
> +    enum class viewStates { MAIN, ADMIN };
Done ✅

2019-03-16 06:30 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
Oh not nvm, you don't need quotation marks at all for the stylesheet

2019-03-16 06:37 UTC, RogChav commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
took them out, good to go

2019-03-16 06:38 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +background-color: &quot;#B19CD9&quot;;
No change was made 👀

2019-03-16 06:57 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +    // Toggle hide on the Top five NavItems "back" to -> "Delete A\nRestaurant"
Out of date comment

2019-03-16 06:59 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +            m_navbar->setEnabled(!m_navbar->isEnabled());
Why not `setEnabled(true);`? Would make it much simpler.

2019-03-16 07:02 UTC, ChrisRzech commented on src/windows/mainwindow.ui
> +         <cursorShape>ForbiddenCursor</cursorShape>
Why are we using `ForbiddenCursor` for all these views?

2019-03-16 07:08 UTC, ChrisRzech approved these changes
Ok looks good, you are clear to land ✈️

2019-03-16 07:08 UTC, ChrisRzech commented on src/widgets/navbar.cpp
> +
👀

2019-03-16 07:08 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +/*Swich views for stacks in mainView within the mainWindow page (page 1) in centralStack*/
👀

2019-03-16 07:08 UTC, ChrisRzech commented on src/windows/mainwindow.cpp
> +            m_navbar->setEnabled(!m_navbar->isEnabled());
👀

2019-03-16 07:16 UTC, merged