Show the admin UI button if the user is an admin
fast-food-finder-associates/FastFoodFinder pull request #41
Opened 2019-03-22 06:35 UTC by ChrisRzech

### Key features
* Checks if the last login type was an admin; if it is, show the admin UI button.

### Future Improvements
* none

### Notes
none

2019-03-22 23:56 UTC, jthomas2234 commented
wow nice !

2019-03-23 00:03 UTC, typokign requested changes
cmon kris

2019-03-23 00:03 UTC, dacruz21 commented on src/windows/mainwindow.cpp
> +        m_navbar->item(3)->setHidden(Login::getType() == Login::Type::ADMIN ? false : true);
`Login::getType() != Login::Type::ADMIN`

2019-03-23 00:03 UTC, dacruz21 commented on src/windows/mainwindow.cpp
> +        m_navbar->item(3)->setHidden(Login::getType() == Login::Type::ADMIN ? true : false);
`Login::getType() == Login::Type::ADMIN`

2019-03-23 00:05 UTC, ChrisRzech commented
PR will be outdated soon, closing.

2019-03-23 00:05 UTC, closed without merging